version: 2
jobs:
  build:
    working_directory: ~/Flask-Context
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements_dev.txt
      - run:
          command: |
            . venv/bin/activate
            nosetests --with-coverage
      - store_artifacts:
          path: coverage/
          destination: cov-html 

